name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web

      - run: |
          cd build
          mkdir web-deploy
          cd web-deploy
          git config --global user.email "alexlink2004@gmail.com"
          git config --global user.name "alexlink2004"
          git init
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/alexlink2004/manufacturing_glossary.git
          # Check if gh-pages branch exists
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            git checkout --orphan gh-pages
            # No need to git rm -rf . here because the orphan branch has no files
          else
            git fetch origin gh-pages
            git checkout -b gh-pages origin/gh-pages
          fi
          # copy the build that is there in ROOT/build/web into ROOT/build/web-deploy
          cp -R ../web/* .
          git status
          git add .
          echo "Committing to gh-pages: ${{ github.event.head_commit.message }}"
          git commit -m "${{ github.event.head_commit.message }}"
          git push --set-upstream origin gh-pages
      
      
