name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release

      # Web deploy now is contained in build/web directory
      - run: |
          cd build
          mkdir web-deploy
          cd web-deploy
          git config --global user.email "alexlink2004@gmail.com"
          git config --global user.name "alexlink2004"
          git config --global init.defaultBranch main
          git init
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/alexlink2004/manufacturing_glossary.git
          # Check if gh-pages branch exists
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
          else
            git fetch origin gh-pages
            git switch gh-pages
          fi
          # copy the build that is there in ROOT/build/web into ROOT/build/web-deploy
          cp -R ../web/* .
          git status
          git add .
          echo "Committing to gh-pages: ${{ github.event.head_commit.message }}"
          git commit -m "${{ github.event.head_commit.message }}"
          git push --set-upstream origin gh-pages
